#@ load("@ytt:md5", "md5")
#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:sha256", "sha256")
#@ load("@ytt:base64", "base64")

#@ configMD5 = md5.sum(json.encode(data.values))
#@ configSHA256 = sha256.sum(json.encode(data.values))
#@ configEncoded = base64.encode(json.encode(data.values))
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline
data:
  data: #@ configEncoded
  config-md5: #@ configMD5
  config-sha256: #@ configSHA256